# Generated by Django 6.0.1 on 2026-03-03 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portale', '0004_alter_tab_statistiche_misuratori_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabTipologiaTurbina',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descrizione', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tab_tipologia_turbina',
                'managed': False,
            },
        ),
    ]
