# Generated by Django 6.0.1 on 2026-03-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portale', '0005_tabtipologiaturbina'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabImpianti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('indirizzo', models.CharField(blank=True, max_length=100, null=True)),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tab impianti',
                'db_table': 'tab_impianti',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TabTurbinaParametri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eta0', models.DecimalField(decimal_places=6, max_digits=8)),
                ('eta_max', models.DecimalField(decimal_places=6, max_digits=8)),
                ('x0', models.DecimalField(decimal_places=6, max_digits=8)),
                ('al', models.DecimalField(decimal_places=6, max_digits=12)),
                ('ar', models.DecimalField(decimal_places=6, max_digits=12)),
                ('kl', models.DecimalField(decimal_places=3, max_digits=6)),
                ('kr', models.DecimalField(decimal_places=3, max_digits=6)),
                ('q_min_ls', models.DecimalField(decimal_places=3, max_digits=10)),
                ('q_max_ls', models.DecimalField(decimal_places=3, max_digits=10)),
                ('metodo', models.CharField(blank=True, max_length=50, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tab turbina parametri',
                'db_table': 'tab_turbina_parametri',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TabTurbine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('salto_nominale_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('salto_netto_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('portata_nominale_ls', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('portata_min_ls', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('portata_max_ls', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('potenza_nominale_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rendimento_nominale', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tab turbine',
                'db_table': 'tab_turbine',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='tabtipologiaturbina',
            options={'managed': False, 'verbose_name_plural': 'Tab tipologia turbina'},
        ),
    ]
